## Example for Data Processing (Part 1)

#### **TO DO**:
- Insert File > (define header, components name) > Data Processing and Separation >> Define Features and Targets >> Define Data type


*File: Dados de defeito enviados.xlsx*

In [1]:
import file
import ipywidgets as widgets

path = file.gui_fname()
path = path.decode('latin-1')
print("Filename: ", path)
header = 0

def f(x):
    return x

x=widgets.IntSlider(min=0, max=5, step=1, value=0, description="Header:")
x

Filename:  C:/Users/JTavares/Documents/GitHub/Tese/Tese/1. data/1 - data/Dados de defeito enviados 1.xlsx

IntSlider(value=0, description='Header:', max=5)

In [2]:
import pandas as pd
import numpy as np
import dateutil.parser
import datetime
import os

name, extension = os.path.splitext(path)
header = x.value

if "xls" in extension:
    data = pd.read_excel(path, header=header, sheet_name=None)
# data = pd.read_excel(r'Qnt prod__Dados_João.xlsx', header=0, sheet_name=None)
elif "csv" in extension:
    df = pd.read_csv(path, header=header)

if "xls" in extension:    
    df = pd.DataFrame()
    for key, value in data.items():
        df = df.append(pd.DataFrame(data[key]), ignore_index=True)
        
    df.rename(columns={'Unnamed: 0':'Componentes'}, inplace=True)
    
for k in df.keys():
    if not isinstance(k, str):
        df = df.rename(columns={k: str(k)})

display(df.head())

,Data,Processo_ P,Quant. Prod.,Caracteristica T,Caracteristica L,Comp.,Larg.,Espess.,Caracteristica A,T (ºC),%HR,Caracteristica MF/HF,Dose,Refugo,Reparações,Total c/Defeito,% c/Defeito
0,2020-10-15 00:00:00,P2,98,TA,Hil,140,38,5.0,CONC,25.0,31.0,NaN,NaN,NaN,NaN,0,0.000000
1,2020-10-15 00:00:00,P2,200,PE,Hil,38,38,5.0,ESVG,25.0,31.0,NaN,NaN,NaN,NaN,0,0.000000
2,2020-10-15 00:00:00,P2,62,CO,Sto,70,30,5.0,CLVG,25.0,31.0,NaN,NaN,NaN,NaN,0,0.000000
3,2020-10-15 00:00:00,P2,92,CO,Sto,70,30,5.0,CLVG,25.0,31.0,NaN,NaN,NaN,NaN,0,0.000000
4,2020-10-16 00:00:00,P1,152,LA,Pom,224,34,3.0,NG,14.0,48.0,NaN,NaN,5.0,NaN,5,0.032895

In [3]:
# from ipywidgets import Checkbox, interact
# from IPython.display import display

# l = df1.keys()
# chk = [Checkbox(description=a) for a in l]

# def updatePlot(**kwargs):
#     print([(k,v) for k, v in kwargs.items()])

# interact(updatePlot, **{c.description: c.value for c in chk})

In [9]:
from ipywidgets import VBox, HBox, Checkbox, Button

l = df.keys()
chk = [Checkbox(description=str(a), value=True) for a in l]
chk2 = [Checkbox(description=str(a)) for a in l]
w = widgets.IntSlider(value=19, min=1, max=26, description='Code of interest:')

lst = [[], [], []] ; lst2 = [[], [], []]
for i in range(len(chk)):
    lst[i%3].append(chk[i])
    lst2[i%3].append(chk2[i])
    
    
tab1 = HBox([VBox(lst[0]), VBox(lst[1]), VBox(lst[2])])
tab2 = HBox([VBox(lst2[0]), VBox(lst2[1]), VBox(lst2[2])])


tab = widgets.Tab(children=[tab1, tab2])
tab.set_title(0, 'Features')
tab.set_title(1, 'Output')
VBox(children=[tab])

VBox(children=(Tab(children=(HBox(children=(VBox(children=(Checkbox(value=True, description='Data'), Checkbox(…

In [14]:
def get_month(s):
    month_dict = {1: "jan", 2:"fev", 3:"mar", 4: "abr", 5:"mai", 6:"jun", 7: "jul", 8:"ago", 9:"set", 10: "out", 11:"nov", 12:"dec"}
    for month in month_dict:
        if month_dict[month] in s:
            return month
        
for date in df["Data"]:
    if not isinstance(date, datetime.date):
        if "/" in date:
            d = date.split("/")
            day, month, year = int(d[0]), int(d[1]), int(d[2])
#             print("day", day, "month", month, "year", year)
        else:
            print("date: ", date)
    else:
        day, month, year = date.day, date.month, date.year
    
    newdate = datetime.date(year=year,day=day,month=month)
    weekday = newdate.weekday()

df['Data'].replace(date, newdate, inplace=True)
df['Data'] = df['Data'].apply(pd.to_datetime)
df['day'] = pd.DatetimeIndex(df['Data']).day
df['month'] = pd.DatetimeIndex(df['Data']).month
df['year'] = pd.DatetimeIndex(df['Data']).year
df['week day'] = pd.DatetimeIndex(df['Data']).weekday


df['months'] = df['Data'].iloc[0]

print(df.dtypes)

df['months'] = ((df['Data'] - df['months'])/np.timedelta64(1, 'M')).astype(int)
display(df.head())

Data                    datetime64[ns]
Processo_ P                     object
Quant. Prod.                     int64
Caracteristica T                object
Caracteristica L                object
Comp.                            int64
Larg.                            int64
Espess.                        float64
Caracteristica A                object
T (ºC)                         float64
%HR                            float64
Caracteristica MF/HF            object
Dose                           float64
Refugo                         float64
Reparações                     float64
Total c/Defeito                  int64
% c/Defeito                    float64
day                              int64
month                            int64
year                             int64
week day                         int64
months                  datetime64[ns]
dtype: object

,Data,Processo_ P,Quant. Prod.,Caracteristica T,Caracteristica L,Comp.,Larg.,Espess.,Caracteristica A,T (ºC),...,Dose,Refugo,Reparações,Total c/Defeito,% c/Defeito,day,month,year,week day,months
0,2020-10-15,P2,98,TA,Hil,140,38,5.0,CONC,25.0,...,NaN,NaN,NaN,0,0.000000,15,10,2020,3,0
1,2020-10-15,P2,200,PE,Hil,38,38,5.0,ESVG,25.0,...,NaN,NaN,NaN,0,0.000000,15,10,2020,3,0
2,2020-10-15,P2,62,CO,Sto,70,30,5.0,CLVG,25.0,...,NaN,NaN,NaN,0,0.000000,15,10,2020,3,0
3,2020-10-15,P2,92,CO,Sto,70,30,5.0,CLVG,25.0,...,NaN,NaN,NaN,0,0.000000,15,10,2020,3,0
4,2020-10-16,P1,152,LA,Pom,224,34,3.0,NG,14.0,...,NaN,5.0,NaN,5,0.032895,16,10,2020,4,0

In [6]:
# df.drop(columns = ["Day", "Month", "Year"], inplace=True)
display(df.dtypes)
display(df[["Data", "day", "month", "year", "week day", "months"]])
# Monday is 0 and Sunday is 6

Data                    datetime64[ns]
Processo_ P                     object
Quant. Prod.                     int64
Caracteristica T                object
Caracteristica L                object
Comp.                            int64
Larg.                            int64
Espess.                        float64
Caracteristica A                object
T (ºC)                         float64
%HR                            float64
Caracteristica MF/HF            object
Dose                           float64
Refugo                         float64
Reparações                     float64
Total c/Defeito                  int64
% c/Defeito                    float64
day                              int64
month                            int64
year                             int64
week day                         int64
months                           int32
dtype: object

           Data  day  month  year  week day  months
0    2020-10-15   15     10  2020         3       0
1    2020-10-15   15     10  2020         3       0
2    2020-10-15   15     10  2020         3       0
3    2020-10-15   15     10  2020         3       0
4    2020-10-16   16     10  2020         4       0
...         ...  ...    ...   ...       ...     ...
1067 2021-06-25   25      6  2021         4       8
1068 2021-06-25   25      6  2021         4       8
1069 2021-06-26   26      6  2021         5       8
1070 2021-06-26   26      6  2021         5       8
1071 2021-06-26   26      6  2021         5       8

[1072 rows x 6 columns]

In [7]:
dfcolumns = []
for fc in chk:
    if fc.value == True:
        dfcolumns.append(fc.description)

outcolumns = []
for fc in chk2:
    if fc.value == True:
        outcolumns.append(fc.description)

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

dfcolumns =  []
outcolumns =  []

In [18]:
df1=df.copy()

dfcolumns =  ['Processo_ P', 'Quant. Prod.', 'Caracteristica T', 'Caracteristica L', 'Comp.',
              'Larg.', 'Espess.', 'Caracteristica A', 'T (ºC)', '%HR', 'month', 'year', 'week day', 'months']
outcolumns =  ['Quant. Prod.', 'Total c/Defeito']

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

dfcolumns =  ['Processo_ P', 'Quant. Prod.', 'Caracteristica T', 'Caracteristica L', 'Comp.', 'Larg.', 'Espess.', 'Caracteristica A', 'T (ºC)', '%HR', 'month', 'year', 'week day', 'months']
outcolumns =  ['Quant. Prod.', 'Total c/Defeito']

### Define code of interest
First, we will try to understand which features are most likely to influence the output

In [19]:
# cols = df1.columns.tolist()

# cols = cols[-1:] + cols[:-1]

# df1 = df1[cols]

# display(df1.head())

,months,Data,Processo_ P,Quant. Prod.,Caracteristica T,Caracteristica L,Comp.,Larg.,Espess.,Caracteristica A,...,Caracteristica MF/HF,Dose,Refugo,Reparações,Total c/Defeito,% c/Defeito,day,month,year,week day
0,0,2020-10-15,P2,98,TA,Hil,140,38,5.0,CONC,...,NaN,NaN,NaN,NaN,0,0.000000,15,10,2020,3
1,0,2020-10-15,P2,200,PE,Hil,38,38,5.0,ESVG,...,NaN,NaN,NaN,NaN,0,0.000000,15,10,2020,3
2,0,2020-10-15,P2,62,CO,Sto,70,30,5.0,CLVG,...,NaN,NaN,NaN,NaN,0,0.000000,15,10,2020,3
3,0,2020-10-15,P2,92,CO,Sto,70,30,5.0,CLVG,...,NaN,NaN,NaN,NaN,0,0.000000,15,10,2020,3
4,0,2020-10-16,P1,152,LA,Pom,224,34,3.0,NG,...,NaN,NaN,5.0,NaN,5,0.032895,16,10,2020,4

In [20]:
import ipywidgets as widgets
from IPython.display import display

df1 = pd.DataFrame()

for dc in dfcolumns:
    df1[dc] = df[dc]

for oc in outcolumns:
    oc1 = "out_"+oc
    df1[oc1] = df[oc].replace(" ", 0)
    df1[oc1].fillna(0, inplace=True)
    df1[oc1] = df1[oc1].astype(int)

display(df1.head())
df1.dtypes

,Processo_ P,Quant. Prod.,Caracteristica T,Caracteristica L,Comp.,Larg.,Espess.,Caracteristica A,T (ºC),%HR,month,year,week day,months,out_Quant. Prod.,out_Total c/Defeito
0,P2,98,TA,Hil,140,38,5.0,CONC,25.0,31.0,10,2020,3,0,98,0
1,P2,200,PE,Hil,38,38,5.0,ESVG,25.0,31.0,10,2020,3,0,200,0
2,P2,62,CO,Sto,70,30,5.0,CLVG,25.0,31.0,10,2020,3,0,62,0
3,P2,92,CO,Sto,70,30,5.0,CLVG,25.0,31.0,10,2020,3,0,92,0
4,P1,152,LA,Pom,224,34,3.0,NG,14.0,48.0,10,2020,4,0,152,5

Processo_ P             object
Quant. Prod.             int64
Caracteristica T        object
Caracteristica L        object
Comp.                    int64
Larg.                    int64
Espess.                float64
Caracteristica A        object
T (ºC)                 float64
%HR                    float64
month                    int64
year                     int64
week day                 int64
months                   int32
out_Quant. Prod.         int32
out_Total c/Defeito      int32
dtype: object

In [21]:
df1 = df1[df1['out_Total c/Defeito']<df1['out_Quant. Prod.']]
df1 = df1.astype({'months': 'int32'})

### Export to CSV

In [22]:
df1.to_csv(name + r' - processed.csv', index = False)

---
### Hide code

In [202]:
# from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
The raw code for this IPython notebook is by default hidden for easier reading.
To toggle on/off the raw code, click <a href="javascript:code_toggle()">here</a>.''')