# Example for Data Processing (Part 1)

#### **TO DO**:
- Insert File > (define header, components name) > Data Processing and Separation >> Define Features and Targets >> Define Data type


*File 1: Copy of Printing Plant Analyse 2020.xlsx* ; *File 2: exportOP_ano_corrigido.xlsx* ; 
*File 3: export2.xlsx* ; *File 4: export1.xlsx*

## Import File

In [2]:
import file
import ipywidgets as widgets

path = file.gui_fname()
path = path.decode('latin-1')
print("Filename 1: ", path)
header = 0

def f(x):
    return x

x=widgets.IntSlider(min=0, max=5, step=1, value=0, description="Header:")
x

Filename 1:  C:/Users/JTavares/OneDrive - Universidade de Lisboa/IST/data/1. raw data/Copy of Printing Plant Analyse 2020 1.csv

IntSlider(value=0, description='Header:', max=5)

In [3]:
import pandas as pd
pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np
import dateutil.parser
import datetime
import os

name, extension = os.path.splitext(path)
header = x.value

if "xls" in extension or "XLS" in extension:
    data = pd.read_excel(path, header=header, sheet_name=None)
elif "csv" in extension:
    df1 = pd.read_csv(path, header=header)

if "xls" in extension or "XLS" in extension:   
    df1 = pd.DataFrame()
    for key, value in data.items():
        df1 = df1.append(pd.DataFrame(data[key]), ignore_index=True)
        
    
for k in df1.keys():
    if not isinstance(k, str):
        df1 = df1.rename(columns={k: str(k)})

display(df1.head())

,aa,ab,ac,Grupo Mercadorias,ad,ae,af,Hierarquia prod,Ordem,Material,...,Qtd.confirmada,UM,Iníc.real,DtaRealFim,Qtd.teórica,Qtd.confirmada.1,FOL,Mês,DD,controlo
0,1.000235e+09,F01,FR01,BAAAAADAB,FR,F,R,1PLRFCP048000,1.000235e+09,51-49012,...,50.760,TH,2019-03-28 00:00:00,2020-01-06 00:00:00,11587.50,423.0,SHT,1.0,META,1.0
1,1.000235e+09,F01,FI01,BAAAAADAB,FI,F,I,1PLIFTM286000,1.000235e+09,51-43258,...,1.760,TH,2019-03-26 00:00:00,2020-01-10 00:00:00,5305.75,440.0,SHT,1.0,META,1.0
2,1.000239e+09,F01,FI01,BAAAAADAB,FI,F,I,1PLIFTM286000,1.000239e+09,51-61468,...,0.532,TH,2019-07-09 00:00:00,2020-01-10 00:00:00,5087.50,133.0,SHT,1.0,META,1.0
3,1.000239e+09,C01,CI01,BAAAAADAA,CI,C,I,1PLICTL188197,1.000239e+09,51-62506,...,1.680,TH,2019-07-11 00:00:00,2020-01-23 00:00:00,850.00,210.0,SHT,1.0,PA,1.0
4,1.000242e+09,C01,CA01,BAAAAADAA,CA,C,A,1PLACRO284443,1.000242e+09,51-68234,...,2.534,TH,2019-10-02 00:00:00,2020-01-27 00:00:00,5250.00,1267.0,SHT,1.0,PA,1.0

In [81]:
path2 = file.gui_fname()
path2 = path2.decode('latin-1')
print("Filename 2: ", path2)


def f(x2):
    return x2

x2=widgets.IntSlider(min=0, max=5, step=1, value=0, description="Header:")
y2 = widgets.Text(value='operacoes', placeholder='sheet name', description='Sheet name:', disabled=False)
display(x2,y2)

Filename 2:  C:/Users/JTavares/OneDrive - Universidade de Lisboa/IST/data/1. raw data/20220711_Tese_operacoes_nível 1.xlsx

IntSlider(value=0, description='Header:', max=5)

Text(value='operacoes', description='Sheet name:', placeholder='sheet name')

In [82]:
name2, extension = os.path.splitext(path2)
header = x2.value

if "xls" in extension or "XLS" in extension:
    data2 = pd.read_excel(path2, header=header, sheet_name=None)# y2.value)
elif "csv" in extension:
    df2 = pd.read_csv(path2, header=header)

if "xls" in extension or "XLS" in extension:  
    df2 = pd.DataFrame()
    for key, value in data2.items():
        df2 = df2.append(pd.DataFrame(data2[key]), ignore_index=True)
    
    
for k in df2.keys():
    if not isinstance(k, str):
        df2 = df2.rename(columns={k: str(k)})

display(df2.head())

,Ordem,Operação,n_operations,Centro de trabalho,Txt.breve operação,Tipo de operação,Tipo de operação n2,Quantidade operação (MEINH),Unid.medida operação (=MEINH),Qtd.ordem,Qtd.boa confirmada (MEINH),Qtd.confirmada,Data início real de execução,Hora início real de execução,Data fim real da execução,Hora fim real da execução,Chave de controle,Status do sistema
0,1000231619,10,1,1LE04,APLICAÇÃO DE VERNIZ PIGMENTADO,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722.222,FOL,722,716.0,716,2018-12-21,12:19:43,2018-12-21,12:21:03,PP01,CNPA ENTE IMPR LIB
1,1000231619,20,2,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,722.222,FOL,716,649.0,649,2018-12-21,21:00:49,2018-12-21,21:11:04,PP01,CNPA ENTE IMPR LIB
2,1000231619,30,3,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,722.222,FOL,649,642.0,642,2018-12-21,21:49:16,2019-01-07,17:15:41,PP01,CNPA ENTE IMPR LIB
3,1000231619,40,4,1LI17,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,722.222,FOL,642,595.0,595,2019-01-07,17:26:58,2019-01-07,17:39:57,PP90,CNPA ENTE IMPR LIB
4,1000231619,50,5,1LI05,APLICAÇÃO DE VERNIZ DE ACABAMENTO,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,722.222,FOL,595,579.0,579,2019-01-07,18:37:14,2020-06-18,21:05:35,PP01,CNPA ENTE IMPR LIB

In [6]:
path3 = file.gui_fname()
path3 = path3.decode('latin-1')
print("Filename 3: ", path3)

x3=widgets.IntSlider(min=0, max=5, step=1, value=0, description="Header:")
x3

Filename 3:  C:/Users/JTavares/OneDrive - Universidade de Lisboa/IST/data/1. raw data/export2.XLSX

IntSlider(value=0, description='Header:', max=5)

In [7]:
name3, extension = os.path.splitext(path3)
header = x3.value

if "xls" in extension or "XLS" in extension:
    data3 = pd.read_excel(path3, header=header, sheet_name=None)
elif "csv" in extension:
    df3 = pd.read_csv(path3, header=header)

if "xls" in extension or "XLS" in extension:  
    df3 = pd.DataFrame()
    for key, value in data3.items():
        df3 = df3.append(pd.DataFrame(data3[key]), ignore_index=True)
    
    
for k in df3.keys():
    if not isinstance(k, str):
        df3 = df3.rename(columns={k: str(k)})

display(df3.head())

,Material,Texto breve de material,Util.LisTéc.,LT alternativa,Texto da alternativa,Centro,Unnamed: 6,Nível,Nº item,Componente,...,Denominação,Qtd.componente (UMC),Unid.med.componente,Qtd.fixa,Setor de atividade,Grupo de mercadorias,Marc.p/el.nív.mand.,Stat.mat.todos cent.,Marc.p/el.nív.centro,Stat.mat.espec.cent.
0,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,1,NaN,CLPP,0,0,NaN,51-00855,...,NaN,0.000,NaN,NaN,LI,BAAAAAC,não,NaN,não,NaN
1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,1,NaN,CLPP,0,1,10.0,51-63743,...,NaN,1000.000,FOL,NaN,LT,BAAAAABAD,não,NaN,não,NaN
2,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,1,NaN,CLPP,0,1,150.0,61-00096,...,NaN,17813.000,G,NaN,LI,AAB,não,NaN,não,NaN
3,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,1,NaN,CLPP,0,1,300.0,13-00610,...,NaN,1.042,UN,NaN,LT,AZZZZ,não,NaN,não,NaN
4,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,1,NaN,CLPP,0,1,NaN,51-63743,...,NaN,0.000,NaN,NaN,LT,BAAAAABAD,não,NaN,não,NaN

In [8]:
path4 = file.gui_fname()
path4 = path4.decode('latin-1')
print("Filename 4: ", path4)

x4=widgets.IntSlider(min=0, max=5, step=1, value=0, description="Header:")
x4

Filename 4:  C:/Users/JTavares/OneDrive - Universidade de Lisboa/IST/data/1. raw data/export1.XLSX

IntSlider(value=0, description='Header:', max=5)

In [9]:
name4, extension = os.path.splitext(path4)
header = x4.value

if "xls" in extension or "XLS" in extension:
    data4 = pd.read_excel(path4, header=header, sheet_name=None)
elif "csv" in extension:
    df4_0 = pd.read_csv(path4, header=header)

if "xls" in extension or "XLS" in extension:  
    df4_0 = pd.DataFrame()
    for key, value in data4.items():
        df4_0 = df4_0.append(pd.DataFrame(data4[key]), ignore_index=True)
    
    
for k in df4_0.keys():
    if not isinstance(k, str):
        df4_0 = df4_0.rename(columns={k: str(k)})

display(df4_0.head())

,Material,Texto breve de material,Util.LisTéc.,LT alternativa,Texto da alternativa,Centro,Unnamed: 6,Nível,Nº item,Componente,...,Denominação,Qtd.componente (UMC),Unid.med.componente,Qtd.fixa,Setor de atividade,Grupo de mercadorias,Marc.p/el.nív.mand.,Stat.mat.todos cent.,Marc.p/el.nív.centro,Stat.mat.espec.cent.
0,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,1,NaN,CLPP,0,0,NaN,51-01145,...,NaN,0.000,NaN,NaN,LI,BAAAAADAA,não,NaN,não,QW
1,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,1,MULTICROMIA L17,CLPP,0,1,10.0,51-70836,...,NaN,55.555,FOL,NaN,LI,BAAAAAC,não,NaN,não,NaN
2,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,1,MULTICROMIA L17,CLPP,0,1,30.0,61-08849,...,NaN,629.000,G,NaN,LI,AAGAB,não,NaN,não,NaN
3,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,1,MULTICROMIA L17,CLPP,0,1,180.0,61-14396,...,NaN,499.000,G,NaN,LI,AAGAA,não,NaN,não,NaN
4,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,1,MULTICROMIA L17,CLPP,0,1,200.0,64-00769,...,NaN,4.000,UN,X,LI,AZZAB,não,NaN,não,NaN

In [29]:
print("DataFrame Shape\nFile 1:", df1.shape, " ; File 2:", df2.shape, " ; File 3:", df3.shape, " ; File 4:", df4_0.shape)

DataFrame Shape
File 1: (30675, 22)  ; File 2: (40604, 18)  ; File 3: (56613, 23)  ; File 4: (50502, 23)

## Define features and output

### File 1

In [ ]:
from ipywidgets import VBox, HBox, Checkbox, Button

l = df1.keys()
chk = [Checkbox(description=str(a)) for a in l]
chk2 = [Checkbox(description=str(a)) for a in l]

lst = [[], [], []] ; lst2 = [[], [], []]
for i in range(len(chk)):
    lst[i%3].append(chk[i])
    lst2[i%3].append(chk2[i])
    
    
tab1 = HBox([VBox(lst[0]), VBox(lst[1]), VBox(lst[2])])
tab2 = HBox([VBox(lst2[0]), VBox(lst2[1]), VBox(lst2[2])])


tab = widgets.Tab(children=[tab1, tab2])
tab.set_title(0, 'Features')
tab.set_title(1, 'Output')
VBox(children=[tab])

In [ ]:
dfcolumns = []
for fc in chk:
    if fc.value == True:
        dfcolumns.append(fc.description)

outcolumns = []
for fc in chk2:
    if fc.value == True:
        outcolumns.append(fc.description)

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

In [30]:
dfcolumns =  ['ab', 'ac', 'Grupo Mercadorias', 'ad', 'ae', 'af', 
'Hierarquia prod', 'Ordem', 'Material', 'Qtd.ordem', 'Qtd.confirmada', 'Iníc.real', 'DtaRealFim',
'Mês', 'DD', 'controlo'] 
outcolumns =  [ ]

In [31]:
import ipywidgets as widgets
from IPython.display import display

df1_1 = pd.DataFrame()

for dc in dfcolumns:
    df1_1[dc] = df1[dc]

for oc in outcolumns:
    oc1 = "out_"+oc
    df1_1[oc1] = df1[oc].replace(" ", 0)
    df1_1[oc1].fillna(0, inplace=True)
    df1_1[oc1] = df1_1[oc1].astype(int)

display(df1_1.head())
df1_1.dtypes

,ab,ac,Grupo Mercadorias,ad,ae,af,Hierarquia prod,Ordem,Material,Qtd.ordem,Qtd.confirmada,Iníc.real,DtaRealFim,Mês,DD,controlo
0,F01,FR01,BAAAAADAB,FR,F,R,1PLRFCP048000,1.000235e+09,51-49012,1390.500,50.760,2019-03-28 00:00:00,2020-01-06 00:00:00,1.0,META,1.0
1,F01,FI01,BAAAAADAB,FI,F,I,1PLIFTM286000,1.000235e+09,51-43258,21.223,1.760,2019-03-26 00:00:00,2020-01-10 00:00:00,1.0,META,1.0
2,F01,FI01,BAAAAADAB,FI,F,I,1PLIFTM286000,1.000239e+09,51-61468,20.350,0.532,2019-07-09 00:00:00,2020-01-10 00:00:00,1.0,META,1.0
3,C01,CI01,BAAAAADAA,CI,C,I,1PLICTL188197,1.000239e+09,51-62506,6.800,1.680,2019-07-11 00:00:00,2020-01-23 00:00:00,1.0,PA,1.0
4,C01,CA01,BAAAAADAA,CA,C,A,1PLACRO284443,1.000242e+09,51-68234,10.500,2.534,2019-10-02 00:00:00,2020-01-27 00:00:00,1.0,PA,1.0

ab                    object
ac                    object
Grupo Mercadorias     object
ad                    object
ae                    object
af                    object
Hierarquia prod       object
Ordem                float64
Material              object
Qtd.ordem            float64
Qtd.confirmada       float64
Iníc.real             object
DtaRealFim            object
Mês                  float64
DD                    object
controlo             float64
dtype: object

### File 2

In [13]:
from ipywidgets import VBox, HBox, Checkbox, Button

l = df2.keys()
chk = [Checkbox(description=str(a)) for a in l]
chk2 = [Checkbox(description=str(a)) for a in l]

lst = [[], [], []] ; lst2 = [[], [], []]
for i in range(len(chk)):
    lst[i%3].append(chk[i])
    lst2[i%3].append(chk2[i])
    
    
tab1 = HBox([VBox(lst[0]), VBox(lst[1]), VBox(lst[2])])
tab2 = HBox([VBox(lst2[0]), VBox(lst2[1]), VBox(lst2[2])])


tab = widgets.Tab(children=[tab1, tab2])
tab.set_title(0, 'Features')
tab.set_title(1, 'Output')
VBox(children=[tab])

VBox(children=(Tab(children=(HBox(children=(VBox(children=(Checkbox(value=False, description='Ordem'), Checkbo…

In [ ]:
dfcolumns = []
for fc in chk:
    if fc.value == True:
        dfcolumns.append(fc.description)

outcolumns = []
for fc in chk2:
    if fc.value == True:
        outcolumns.append(fc.description)

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

In [83]:
dfcolumns = ['Ordem', 'n_operations','Operação', 'Centro de trabalho', 'Tipo de operação', 'Tipo de operação n2', 'Qtd.ordem']
outcolumns = ['Qtd.ordem', 'Qtd.confirmada']

In [84]:
import ipywidgets as widgets
from IPython.display import display

df2_1 = pd.DataFrame()

for dc in dfcolumns:
    df2_1[dc] = df2[dc]

for oc in outcolumns:
    oc1 = "out_"+oc
    df2_1[oc1] = df2[oc].replace(" ", 0)
    df2_1[oc1].fillna(0, inplace=True)
    df2_1[oc1] = df2_1[oc1].astype(int)

display(df2_1.head())
df2_1.dtypes

,Ordem,n_operations,Operação,Centro de trabalho,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,out_Qtd.confirmada
0,1000231619,1,10,1LE04,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,716
1,1000231619,2,20,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,649
2,1000231619,3,30,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,642
3,1000231619,4,40,1LI17,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,595
4,1000231619,5,50,1LI05,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,579

Ordem                   int64
n_operations            int64
Operação                int64
Centro de trabalho     object
Tipo de operação       object
Tipo de operação n2    object
Qtd.ordem               int64
out_Qtd.ordem           int32
out_Qtd.confirmada      int32
dtype: object

### File 3

In [ ]:
from ipywidgets import VBox, HBox, Checkbox, Button

l = df3.keys()
chk = [Checkbox(description=str(a)) for a in l]
chk2 = [Checkbox(description=str(a)) for a in l]

lst = [[], [], []] ; lst2 = [[], [], []]
for i in range(len(chk)):
    lst[i%3].append(chk[i])
    lst2[i%3].append(chk2[i])
    
    
tab1 = HBox([VBox(lst[0]), VBox(lst[1]), VBox(lst[2])])
tab2 = HBox([VBox(lst2[0]), VBox(lst2[1]), VBox(lst2[2])])


tab = widgets.Tab(children=[tab1, tab2])
tab.set_title(0, 'Features')
tab.set_title(1, 'Output')
VBox(children=[tab])

In [ ]:
dfcolumns = []
for fc in chk:
    if fc.value == True:
        dfcolumns.append(fc.description)

outcolumns = []
for fc in chk2:
    if fc.value == True:
        outcolumns.append(fc.description)

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

In [36]:
dfcolumns =  ['Material', 'Texto breve de material', 'Nível', 'Nº item', 
'Componente', 'Texto breve objeto', 'Setor de atividade', 'Grupo de mercadorias'] ;
outcolumns =  [ ]

In [37]:
import ipywidgets as widgets
from IPython.display import display

df3_1 = pd.DataFrame()

for dc in dfcolumns:
    df3_1[dc] = df3[dc]

for oc in outcolumns:
    oc1 = "out_"+oc
    df3_1[oc1] = df3[oc].replace(" ", 0)
    df3_1[oc1].fillna(0, inplace=True)
    df3_1[oc1] = df3_1[oc1].astype(int)

display(df3_1.head())
df3_1.dtypes
print("Shape:", df3_1.shape)

,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias
0,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,0,NaN,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,LI,BAAAAAC
1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD
2,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,150.0,61-00096,ESM BRANCO HB-367 A,LI,AAB
3,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,300.0,13-00610,ESTRADO DE MADEIRA 27,LT,AZZZZ
4,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,NaN,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD

Shape: (56613, 8)

### File 4

In [18]:
from ipywidgets import VBox, HBox, Checkbox, Button

l = df4_0.keys()
chk = [Checkbox(description=str(a)) for a in l]
chk2 = [Checkbox(description=str(a)) for a in l]

lst = [[], [], []] ; lst2 = [[], [], []]
for i in range(len(chk)):
    lst[i%3].append(chk[i])
    lst2[i%3].append(chk2[i])
    
    
tab1 = HBox([VBox(lst[0]), VBox(lst[1]), VBox(lst[2])])
tab2 = HBox([VBox(lst2[0]), VBox(lst2[1]), VBox(lst2[2])])


tab = widgets.Tab(children=[tab1, tab2])
tab.set_title(0, 'Features')
tab.set_title(1, 'Output')
VBox(children=[tab])

VBox(children=(Tab(children=(HBox(children=(VBox(children=(Checkbox(value=False, description='Material'), Chec…

In [19]:
dfcolumns = []
for fc in chk:
    if fc.value == True:
        dfcolumns.append(fc.description)

outcolumns = []
for fc in chk2:
    if fc.value == True:
        outcolumns.append(fc.description)

print("dfcolumns = ", dfcolumns)
print("outcolumns = ", outcolumns)

dfcolumns =  []
outcolumns =  []

In [38]:
import ipywidgets as widgets
from IPython.display import display

df4_1 = pd.DataFrame()

for dc in dfcolumns:
    df4_1[dc] = df4_0[dc]

for oc in outcolumns:
    oc1 = "out_"+oc
    df4_1[oc1] = df4_0[oc].replace(" ", 0)
    df4_1[oc1].fillna(0, inplace=True)
    df4_1[oc1] = df4_1[oc1].astype(int)

display(df4_1.head())
df4_1.dtypes
print("Shape:", df4_1.shape)

,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias
0,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",0,NaN,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",LI,BAAAAADAA
1,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,10.0,51-70836,"F.PREP BD-CY 99X143,5 EC WC Sicasa",LI,BAAAAAC
2,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,30.0,61-08849,VERNIZ OURO REF. 2201-305/A PPG,LI,AAGAB
3,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,180.0,61-14396,VRN ACAB 815.346,LI,AAGAA
4,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,200.0,64-00769,CHAPAS ELE MX 40 1095x1220 (7449416)0600,LI,AZZAB

Shape: (50502, 8)

## Corte de Folha and Embalamento +  Centro de Trabalho

#### Data processing

First, we will only look for examples of "Corte de Folha" and "Embalamento", which corresponds to the last operation done.

In [85]:
# columns = ["CORTE DE FOLHA"] #, "EMBALAMENTO"]

# df4 = df2_1[df2_1['Tipo de operação'].isin(columns)]
df4 = df2_1

df4['dif'] = df4['out_Qtd.ordem'] - df4['out_Qtd.confirmada']

df4_02 = df4[df4['dif'] < -5]
df4_01 = df4

display(df4_01.head())
print("Shape:", df4_01.shape)

print('\n')
print('*'*50)
print('Negative Defects percentage')
display(df4_02.head())
print("Shape:", df4_02.shape)

,Ordem,n_operations,Operação,Centro de trabalho,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,out_Qtd.confirmada,dif
0,1000231619,1,10,1LE04,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,716,6
1,1000231619,2,20,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,649,67
2,1000231619,3,30,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,642,7
3,1000231619,4,40,1LI17,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,595,47
4,1000231619,5,50,1LI05,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,579,16

Shape: (40604, 10)


**************************************************
Negative Defects percentage

,Ordem,n_operations,Operação,Centro de trabalho,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,out_Qtd.confirmada,dif
37,1000242105,1,10,1LE08,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,3125,3125,3138,-13
55,1000242475,2,10,1LE04,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ OURO,1117,1117,1166,-49
61,1000242582,3,30,1LE08,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ INCOLOR,1320,1320,1383,-63
67,1000242644,5,40,1EM01,EMBALAMENTO,EMBALAMENTO,752,752,1402,-650
68,1000242736,1,10,1LE08,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,2296,2296,2307,-11

Shape: (6838, 10)

In [86]:
# order_columns = ["CORTE DE FOLHA"] #, "EMBALAMENTO"]

# df4 = df2_1[df2_1['Txt.breve operação'].isin(order_columns)]

# # Convert values to integer
# cols = ['Quantidade operação (MEINH)']
# df4[cols] = df4[cols].astype(int)

# Calculate number of defects
df4['out_defects'] = df4['out_Qtd.ordem'] - df4['out_Qtd.confirmada']

# Remove rows without confirmed quantity
df4.drop(df4[df4["out_Qtd.confirmada"] == 0].index, inplace=True)

# Remove rows with NaN
df4.drop(df4[df4["Tipo de operação"] == "NaN"].index, inplace=True)

# df.drop(df[df.score < 50].index, inplace=True)

### Centro de Trabalho

In [87]:
ct_columns = df4["Centro de trabalho"].unique()

df4["CT"] = df4["Centro de trabalho"].str[1:]

df4.head()

,Ordem,n_operations,Operação,Centro de trabalho,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,out_Qtd.confirmada,dif,out_defects,CT
0,1000231619,1,10,1LE04,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,716,6,6,LE04
1,1000231619,2,20,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,649,67,67,LE02
2,1000231619,3,30,1LE02,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,642,7,7,LE02
3,1000231619,4,40,1LI17,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,595,47,47,LI17
4,1000231619,5,50,1LI05,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,579,16,16,LI05

In [88]:
# Drop column
df4.drop(['Centro de trabalho', 'Operação', "out_Qtd.confirmada"], axis=1, inplace=True)

display(df4.head())
print("Shape df4:", df4.shape)
print("Shape df1:", df1_1.shape)

,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT
0,1000231619,1,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,6,6,LE04
1,1000231619,2,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,67,67,LE02
2,1000231619,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,7,7,LE02
3,1000231619,4,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,47,47,LI17
4,1000231619,5,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,16,16,LI05

Shape df4: (40567, 9)
Shape df1: (30675, 16)

### Join dataframes from "Ordem"

In [89]:
df1_1.rename(columns={"Qtd.ordem": "Qtd.ordem_old"}, inplace=True)

df5 = df4.set_index('Ordem').join(df1_1.set_index('Ordem'))

df5.reset_index(inplace=True)

display(df5.head())
print("Shape:", df5.shape)

,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,ab,...,af,Hierarquia prod,Material,Qtd.ordem_old,Qtd.confirmada,Iníc.real,DtaRealFim,Mês,DD,controlo
0,1000231619,1,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,6,6,LE04,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
1,1000231619,2,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,67,67,LE02,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
2,1000231619,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,7,7,LE02,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
3,1000231619,4,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,47,47,LI17,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
4,1000231619,5,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,16,16,LI05,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0

Shape: (41146, 24)

In [90]:
# using dropna() function  
df5 = df5.dropna()
print(df5.isna().sum())
print("Shape:", df5.shape)

a = df5['Grupo Mercadorias'].unique()
a

Ordem                  0
n_operations           0
Tipo de operação       0
Tipo de operação n2    0
Qtd.ordem              0
out_Qtd.ordem          0
dif                    0
out_defects            0
CT                     0
ab                     0
ac                     0
Grupo Mercadorias      0
ad                     0
ae                     0
af                     0
Hierarquia prod        0
Material               0
Qtd.ordem_old          0
Qtd.confirmada         0
Iníc.real              0
DtaRealFim             0
Mês                    0
DD                     0
controlo               0
dtype: int64
Shape: (39028, 24)

array(['BAAAAADAA', 'BAAAAADAB', 'BAAAAAC'], dtype=object)

In [91]:
df5.head()

,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,ab,...,af,Hierarquia prod,Material,Qtd.ordem_old,Qtd.confirmada,Iníc.real,DtaRealFim,Mês,DD,controlo
0,1000231619,1,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,6,6,LE04,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
1,1000231619,2,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,67,67,LE02,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
2,1000231619,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,7,7,LE02,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
3,1000231619,4,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,47,47,LI17,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0
4,1000231619,5,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,16,16,LI05,C06,...,I,1PLICRO108132,51-62256,13.0,10.44,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0

In [92]:
df_teste = df5

df_teste["data_teste"] = df_teste['Iníc.real'].str.split(" ", n=1).str[0]
df_teste['start_date'] = pd.to_datetime(df_teste["data_teste"], format = '%Y-%m-%d', errors='coerce')

df_teste["data_teste"] = df_teste['DtaRealFim'].str.split(" ", n=1).str[0]
df_teste['end_date'] = pd.to_datetime(df_teste["data_teste"], format = '%Y-%m-%d', errors='coerce')

df_teste['Difference'] = (df_teste['end_date'] - df_teste['start_date']).dt.days

df_teste['week_day'] = df_teste['end_date'].dt.dayofweek

df_teste.head()

,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,ab,...,Iníc.real,DtaRealFim,Mês,DD,controlo,data_teste,start_date,end_date,Difference,week_day
0,1000231619,1,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,6,6,LE04,C06,...,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0,2020-06-22,2018-12-21,2020-06-22,549.0,0.0
1,1000231619,2,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,67,67,LE02,C06,...,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0,2020-06-22,2018-12-21,2020-06-22,549.0,0.0
2,1000231619,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,7,7,LE02,C06,...,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0,2020-06-22,2018-12-21,2020-06-22,549.0,0.0
3,1000231619,4,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,47,47,LI17,C06,...,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0,2020-06-22,2018-12-21,2020-06-22,549.0,0.0
4,1000231619,5,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,16,16,LI05,C06,...,2018-12-21 00:00:00,2020-06-22 00:00:00,6.0,META,1.0,2020-06-22,2018-12-21,2020-06-22,549.0,0.0

## Material description

### File 3

#### F1 (dimensions and characteristics)

In [55]:
## Grupo de mercadorias para F1: BAAAAABAC and BAAAAABAD
f1 = ["BAAAAABAC" , "BAAAAABAD"]

df3_2 = df3_1[df3_1['Grupo de mercadorias'].isin(f1)]
df3_2.drop_duplicates(subset='Material', keep='first', inplace=True)
df3_2.reset_index(inplace=True)


display(df3_2.head())
print("Shape df3 2:", df3_2.shape)
print("Shape df3 1:", df3_1.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias
0,1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD
1,8,51-00882,F.PREP BD-RC 180x120x274 EC WC,1,10.0,51-43694,"F1 835x1106x0,23 E2,8 TS275",LT,BAAAAABAD
2,27,51-01163,BD-CY 99x118 1T ST ESMALTE,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD
3,68,51-02791,BD-RC 106x76x165 DISSOLVENTE,2,10.0,51-45152,"F1 850x1006x0,23 D2,8/2,0 TS275",LT,BAAAAABAD
4,105,51-03931,BD-AE 65X157 2EC WC,1,10.0,51-70012,"F1 833x806,5x0,20 D2,8/2,0 TS275",LT,BAAAAABAD

Shape df3 2: (2060, 9)
Shape df3 1: (56613, 8)

In [56]:
# using dropna() function  
# df5 = df5.dropna()
print(df3_2["Grupo de mercadorias"].isna().sum())

print("Shape df3 2:", df3_2.shape)

0
Shape df3 2: (2060, 9)

In [57]:
columns1 = ['dim1', 'dim2', 'dim3', 'car1', 'car2']

for idx, component in enumerate(df3_2["Texto breve objeto"]):
    c = component.split(" ")
    c = list(filter(None, c))
    if len(c) == 4:
        if 'x' in c[1]:
            c1 = c[1].split("x")
        elif 'X' in c[1]:
            c1 = c[1].split("X")
        dim1 = float(c1[0].replace(',','.')); dim2 = float(c1[1].replace(',','.')); dim3 = float(c1[2].replace(',','.'))
        car1 = c[2]; car2 = c[3]
    column_indexer = {'dim1':dim1, 'dim2':dim2, 'dim3':dim3, 'car1':car1, 'car2':car2}
    for x in column_indexer:
        df3_2.loc[idx,x]=column_indexer[x]
    
display(df3_2.head())
print("Shape df3 2:", df3_2.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2
0,1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,1075.0,0.25,"D2,8/2,0",TS275
1,8,51-00882,F.PREP BD-RC 180x120x274 EC WC,1,10.0,51-43694,"F1 835x1106x0,23 E2,8 TS275",LT,BAAAAABAD,835.0,1106.0,0.23,"E2,8",TS275
2,27,51-01163,BD-CY 99x118 1T ST ESMALTE,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550
3,68,51-02791,BD-RC 106x76x165 DISSOLVENTE,2,10.0,51-45152,"F1 850x1006x0,23 D2,8/2,0 TS275",LT,BAAAAABAD,850.0,1006.0,0.23,"D2,8/2,0",TS275
4,105,51-03931,BD-AE 65X157 2EC WC,1,10.0,51-70012,"F1 833x806,5x0,20 D2,8/2,0 TS275",LT,BAAAAABAD,833.0,806.5,0.20,"D2,8/2,0",TS275

Shape df3 2: (2060, 14)

#### Esm. Branco

In [58]:
# Esm Branco
esm_branco = ["AAB"]
      
df3_3 = df3_1[df3_1['Grupo de mercadorias'].isin(esm_branco)]
df3_3.drop_duplicates(subset='Material', keep='first', inplace=True)
df3_3.reset_index(inplace=True)

df3_3["esm"] = df3_3["Texto breve objeto"]
sub_df = df3_3[["Material", "esm"]]

# Join df with esm. branco and df with f1
df3_4 = df3_2.merge(sub_df, how='left', on='Material')

display(df3_4.head())
print("Shape df3 4:", df3_4.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2,esm
0,1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,1075.0,0.25,"D2,8/2,0",TS275,ESM BRANCO HB-367 A
1,8,51-00882,F.PREP BD-RC 180x120x274 EC WC,1,10.0,51-43694,"F1 835x1106x0,23 E2,8 TS275",LT,BAAAAABAD,835.0,1106.0,0.23,"E2,8",TS275,ESM BRANCO HB-367 A
2,27,51-01163,BD-CY 99x118 1T ST ESMALTE,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550,ESM BRANCO HB-367 A
3,68,51-02791,BD-RC 106x76x165 DISSOLVENTE,2,10.0,51-45152,"F1 850x1006x0,23 D2,8/2,0 TS275",LT,BAAAAABAD,850.0,1006.0,0.23,"D2,8/2,0",TS275,ESM BRANCO HB-367 A
4,105,51-03931,BD-AE 65X157 2EC WC,1,10.0,51-70012,"F1 833x806,5x0,20 D2,8/2,0 TS275",LT,BAAAAABAD,833.0,806.5,0.20,"D2,8/2,0",TS275,ESM BRANCO HB-367 A

Shape df3 4: (2060, 15)

#### Estrato Madeira

In [59]:
# Estrato Madeira
estrado = ["AZZZZ"]
      
df3_3 = df3_1[df3_1['Grupo de mercadorias'].isin(estrado)]
# df3_3.drop_duplicates(subset='Material', keep='first', inplace=True)
df3_3.reset_index(inplace=True)

df3_3["est"] = df3_3["Texto breve objeto"]
sub_df = df3_3[["Material", "est"]]
sub_df = pd.get_dummies(sub_df, columns=["est"])
sub_df = sub_df.groupby("Material").max()

# Join df with esm. branco and df with f1
df3_5 = df3_4.merge(sub_df, how='left', on='Material')

display(df3_5.head())
print("Shape df3 5:", df3_5.shape)
print(df3_5.isna().sum())

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,...,est_ESTRADO DE MADEIRA R10,est_ESTRADO DE MADEIRA R12,est_ESTRADO DE MADEIRA R3,est_ESTRADO DE MADEIRA R4,est_ESTRADO DE MADEIRA R6,est_ESTRADO DE MADEIRA R8,est_ESTRADO DE MADEIRA R9,est_ESTRADO DE MADEIRA RD,est_ESTRADO DE MADEIRA X1,est_ESTRADO DE MADEIRA Z4
0,1,51-00855,F.PREP BD-TL 188 BD-CY 170 EC WC,1,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,...,0,0,0,0,0,0,0,0,0,0
1,8,51-00882,F.PREP BD-RC 180x120x274 EC WC,1,10.0,51-43694,"F1 835x1106x0,23 E2,8 TS275",LT,BAAAAABAD,835.0,...,0,0,0,0,0,0,0,0,0,0
2,27,51-01163,BD-CY 99x118 1T ST ESMALTE,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,...,0,0,0,0,0,0,0,0,0,0
3,68,51-02791,BD-RC 106x76x165 DISSOLVENTE,2,10.0,51-45152,"F1 850x1006x0,23 D2,8/2,0 TS275",LT,BAAAAABAD,850.0,...,0,0,0,0,0,0,0,0,0,0
4,105,51-03931,BD-AE 65X157 2EC WC,1,10.0,51-70012,"F1 833x806,5x0,20 D2,8/2,0 TS275",LT,BAAAAABAD,833.0,...,0,0,0,0,0,0,0,0,0,0

Shape df3 5: (2060, 62)
index                        0
Material                     0
Texto breve de material      0
Nível                        0
Nº item                      0
                            ..
est_ESTRADO DE MADEIRA R8    0
est_ESTRADO DE MADEIRA R9    0
est_ESTRADO DE MADEIRA RD    0
est_ESTRADO DE MADEIRA X1    0
est_ESTRADO DE MADEIRA Z4    0
Length: 62, dtype: int64

In [93]:
# Without Estrato Madeira

df3_5 = df3_4

#### Texto Breve Material

In [94]:
# data processing for Texto breve material

df3_6 = df3_5.copy()

for idx, component in enumerate(df3_6["Texto breve de material"]):
#     print(component)
    flag = 0;
    c = component.split(" ")
    c = list(filter(None, c))
    if len(c) <= 2:
        continue
    else:
        if 'F.PREP' in c[0]:
            f_prep = 1
            car1_1 = c[1]
            if "LI" in car1_1:
                li0_bd1 = 0
            elif "BD" in car1_1:
                li0_bd1 = 1
            try:
                if 'x' in c[2]:
                    c1 = c[2].split("x")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                elif 'X' in c[2]:
                    c1 = c[2].split("X")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                else:
                    try:
                        dim1_1 = float(c[2].replace(',','.')) ; dim1_2 = np.nan
                    except:
                        print("Error with: ", component) ; flag = 1
            except:
                print("Error with: ", component) ; flag = 1
        else:
            f_prep = 0
            car1_1 = c[0]
            if "LI" in car1_1:
                li0_bd1 = 0
            elif "BD" in car1_1:
                li0_bd1 = 1
            try:
                if 'x' in c[1]:
                    c1 = c[1].split("x")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                elif 'X' in c[1]:
                    c1 = c[1].split("X")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                else:
                    try:
                        dim1_1 = float(c[1].replace(',','.')) ; dim1_2 = np.nan
                    except: 
                        print("Error with: ", component) ; flag = 1
            except: 
                print("Error with: ", component) ; flag = 1
        
        if flag == 0:
            column_indexer = {'dim1_1':dim1_1, 'dim1_2':dim1_2, 'car1_1':car1_1, 'f_prep':f_prep, 'li_bd':li0_bd1}
            for x in column_indexer:
                df3_6.loc[idx,x]=column_indexer[x]
    
df3_6.dropna(subset = ["dim1_1"], inplace=True)

display(df3_6.tail())
print("Shape df3 6:", df3_6.shape)

Error with:  LI-RG 188/LI-BT 170 IC/EC GD FOOD N.SPEC
Error with:  BD-CY 284/273x372FT DIN57 2C EC WC(SP M)
Error with:  BD-CY 284/273x235 FT EC WC (SP MKT)
Error with:  F.PREP BD-TL 188/CY 170 IC PGB EC WC0,25
Error with:  LI-LD 190SL 1£ BC BAYERN MUNICH GUNZ REL
Error with:  BD-AE 65x104,4VASO W5 LAV FR E53954-1801
Error with:  BD-AE 65x300CASA J HOGAR LAV.E52512-1902
Error with:  F.PREP BD-AE 65x* IC GD EC WC (COIL 921)
Error with:  F.PREP BD-AE 65x* EC CL (COIL 921)
Error with:  F.PREP BD-AE 65x* EC WC (COIL 921)
Error with:  F.PREP BD-CY 273/284x240 EC WC (TITAN)
Error with:  F.PREP BD-CY 273/284x240 IC GD EC WC
Error with:  F.PREP BD-CY 273/284x463 2EC WC
Error with:  F.PREP BD-CY BD-CY 65x75 EC WC
Error with:  F.PREP BD-CY 99x...IC PGC 2ECWC(NSTH550)
Error with:  F.PREP BD-CY 99x148/60 IC PGC EC WC
Error with:  F.PREP BD-CY 99x... EC 2xWC (NS TH550)
Error with:  BD-CY 267-284X443 FT DIN57 ORO LESI 0,32
Error with:  F.PREP BD-TL 188/CY170 IC PGB EC WC HEST
Error with:  F.PREP BD-TL 188/TC180 IC PGB EC CL HEST
Error with:  F.PREP BD-TL 188/CY 170/TC 180 ECWC HEST
Error with:  F.PREP BD-TL 188/CY 170/TC 180 EC CLHEST
Error with:  F.PREP BD-AE 65x*2xIC GD EC WC(COIL 921)
Error with:  F.PREP BD-TL 188/CY 170/TC 180 ECCL 0,23
Error with:  BD-AE 57x257VASO ZELCO APRES.E54461-2003
Error with:  F.PREP BD-AE 65x* EC WC 1D (COIL 921)
Error with:  BD-AE 65x104,4CON.FRU.BOSQUE E53983-1901
Error with:  F.PREP BD-CY 273/284x240 EC CL (837)
Error with:  F.PREP BD-CY 273/284x372 EC WC (837)
Error with:  F.PREP BD-CY 273/284x445 EC CL (837)
Error with:  F.PREP BD-CY 273/284x463 EC CL (837)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd
2055,56502,51-74063,BD-TL 188x197 1T N TECH EX330 STD.BAS NE,2,10.0,51-63081,"F1 829x1075x0,23 D2,8/2,0 TS275",LT,BAAAAABAD,829.0,1075.0,0.23,"D2,8/2,0",TS275,NaN,188.0,197.0,BD-TL,0.0,1.0
2056,56544,51-74064,BD-TL 188x197 1T N TECH EX370 BTE.BAS NE,2,10.0,51-63081,"F1 829x1075x0,23 D2,8/2,0 TS275",LT,BAAAAABAD,829.0,1075.0,0.23,"D2,8/2,0",TS275,NaN,188.0,197.0,BD-TL,0.0,1.0
2057,56576,51-74073,"F.PREP BD-AE 65x195 EC CL 0,17 (N).",1,10.0,51-73706,"F1 833x798,2x0,17 E2,8 TS290.",LT,BAAAAABAD,833.0,798.2,0.17,"E2,8",TS290.,NaN,65.0,195.0,BD-AE,1.0,1.0
2058,56595,51-74099,LI-LD 190 SL 1£ BC LIDL FAVORINA 2020,2,10.0,51-59623,"F1 819x908x0,15 E2,8 TH520 SCR",LT,BAAAAABAD,833.0,798.2,0.17,"E2,8",TS290.,NaN,190.0,NaN,LI-LD,0.0,0.0
2059,56605,51-74155,"F.PREP LI-LD 286 P IC PGB EC WC 0,34.",1,10.0,51-59255,"F1 730x767,3x0,34 E2,0 TS275 SCR.",LT,BAAAAABAD,833.0,798.2,0.17,"E2,8",TS290.,ESMALTE 135.262,286.0,NaN,LI-LD,1.0,0.0

Shape df3 6: (2027, 20)

In [95]:
print(df3_6.isna().sum())

index                        0
Material                     0
Texto breve de material      0
Nível                        0
Nº item                      0
Componente                   0
Texto breve objeto           0
Setor de atividade           0
Grupo de mercadorias         0
dim1                         0
dim2                         0
dim3                         0
car1                         0
car2                         0
esm                        550
dim1_1                       0
dim1_2                     175
car1_1                       0
f_prep                       0
li_bd                        0
dtype: int64

In [96]:
drop_columns = ['index', 'Texto breve de material', 'Nível', 'Nº item', 'Componente', 'Texto breve objeto', 'Setor de atividade', 'Grupo de mercadorias']
df3_6.drop(drop_columns, axis=1, inplace=True, errors='ignore')

# print(df3_6.nunique())
print(df3_6.keys())

Index(['Material', 'dim1', 'dim2', 'dim3', 'car1', 'car2', 'esm', 'dim1_1',
       'dim1_2', 'car1_1', 'f_prep', 'li_bd'],
      dtype='object')

### File 4

#### F1 (dimensions and characteristics)

In [64]:
## Grupo de mercadorias para F1: BAAAAABAC and BAAAAABAD
f1 = ["BAAAAABAC" , "BAAAAABAD"]

display(df4_1.head())

df4_2 = df4_1[df4_1['Grupo de mercadorias'].isin(f1)]
df4_2.drop_duplicates(subset='Material', keep='first', inplace=True)
df4_2.reset_index(inplace=True)


display(df4_2.head())
print("Shape df4 2:", df4_2.shape)
print("Shape df4 1:", df4_1.shape)

,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias
0,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",0,NaN,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",LI,BAAAAADAA
1,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,10.0,51-70836,"F.PREP BD-CY 99X143,5 EC WC Sicasa",LI,BAAAAAC
2,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,30.0,61-08849,VERNIZ OURO REF. 2201-305/A PPG,LI,AAGAB
3,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,180.0,61-14396,VRN ACAB 815.346,LI,AAGAA
4,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",1,200.0,64-00769,CHAPAS ELE MX 40 1095x1220 (7449416)0600,LI,AZZAB

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias
0,12,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",2,10.0,51-43693,"F1 950x888,8x0,22 D2,8/2,0 TH415",LT,BAAAAABAD
1,37,51-01172,BD-CY 99x118 ST EC CL,1,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD
2,57,51-01215,BD-CY 99x118 1T ST ESMALTE INDUSTRIAL,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD
3,100,51-01615,BD-CY 150x188 25P SALS.SICASAL,2,10.0,51-43971,"F1 950x775x0,26 D2,8/2,0 TH415",LT,BAAAAABAD
4,114,51-01799,BD-TC 180x235 P IC GD EC WC 3KG AZEITONA,2,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD

Shape df4 2: (1840, 9)
Shape df4 1: (50502, 8)

In [65]:
# using dropna() function  
# df5 = df5.dropna()
print(df4_2["Grupo de mercadorias"].isna().sum())

print("Shape df4 2:", df4_2.shape)

0
Shape df4 2: (1840, 9)

In [66]:
columns1 = ['dim1', 'dim2', 'dim3', 'car1', 'car2']

for idx, component in enumerate(df4_2["Texto breve objeto"]):
    c = component.split(" ")
    c = list(filter(None, c))
    if len(c) == 4:
        if 'x' in c[1]:
            c1 = c[1].split("x")
        elif 'X' in c[1]:
            c1 = c[1].split("X")
        dim1 = float(c1[0].replace(',','.')); dim2 = float(c1[1].replace(',','.')); dim3 = float(c1[2].replace(',','.'))
        car1 = c[2]; car2 = c[3]
    column_indexer = {'dim1':dim1, 'dim2':dim2, 'dim3':dim3, 'car1':car1, 'car2':car2}
    for x in column_indexer:
        df4_2.loc[idx,x]=column_indexer[x]
    
display(df4_2.head())
print("Shape df4 2:", df4_2.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2
0,12,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",2,10.0,51-43693,"F1 950x888,8x0,22 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,888.8,0.22,"D2,8/2,0",TH415
1,37,51-01172,BD-CY 99x118 ST EC CL,1,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550
2,57,51-01215,BD-CY 99x118 1T ST ESMALTE INDUSTRIAL,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550
3,100,51-01615,BD-CY 150x188 25P SALS.SICASAL,2,10.0,51-43971,"F1 950x775x0,26 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,775.0,0.26,"D2,8/2,0",TH415
4,114,51-01799,BD-TC 180x235 P IC GD EC WC 3KG AZEITONA,2,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,1075.0,0.25,"D2,8/2,0",TS275

Shape df4 2: (1840, 14)

#### Esm. Branco

In [67]:
# Esm Branco
esm_branco = ["AAB"]
      
df4_3 = df4_1[df4_1['Grupo de mercadorias'].isin(esm_branco)]
df4_3.drop_duplicates(subset='Material', keep='first', inplace=True)
df4_3.reset_index(inplace=True)

df4_3["esm"] = df4_3["Texto breve objeto"]
sub_df = df4_3[["Material", "esm"]]

# Join df with esm. branco and df with f1
df4_4 = df4_2.merge(sub_df, how='left', on='Material')

display(df4_4.head())
print("Shape df4 4:", df4_4.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2,esm
0,12,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",2,10.0,51-43693,"F1 950x888,8x0,22 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,888.8,0.22,"D2,8/2,0",TH415,ESM BRANCO 819.904
1,37,51-01172,BD-CY 99x118 ST EC CL,1,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550,NaN
2,57,51-01215,BD-CY 99x118 1T ST ESMALTE INDUSTRIAL,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,941.8,0.18,"E2,0",TH550,ESM BRANCO HB-367 A
3,100,51-01615,BD-CY 150x188 25P SALS.SICASAL,2,10.0,51-43971,"F1 950x775x0,26 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,775.0,0.26,"D2,8/2,0",TH415,ESM BRANCO 819.904
4,114,51-01799,BD-TC 180x235 P IC GD EC WC 3KG AZEITONA,2,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,1075.0,0.25,"D2,8/2,0",TS275,ESM BRANCO 819.904

Shape df4 4: (1840, 15)

#### Estrato Madeira

In [68]:
# Estrato Madeira
estrado = ["AZZZZ"]
      
df4_3 = df4_1[df4_1['Grupo de mercadorias'].isin(estrado)]
# df4_3.drop_duplicates(subset='Material', keep='first', inplace=True)
df4_3.reset_index(inplace=True)

df4_3["est"] = df4_3["Texto breve objeto"]
sub_df = df4_3[["Material", "est"]]
sub_df = pd.get_dummies(sub_df, columns=["est"])
sub_df = sub_df.groupby("Material").max()

# Join df with esm. branco and df with f1
df4_5 = df4_4.merge(sub_df, how='left', on='Material')

display(df4_5.head())
print("Shape df4 5:", df4_5.shape)

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,...,est_ESTRADO DE MADEIRA R10,est_ESTRADO DE MADEIRA R12,est_ESTRADO DE MADEIRA R3,est_ESTRADO DE MADEIRA R4,est_ESTRADO DE MADEIRA R6,est_ESTRADO DE MADEIRA R8,est_ESTRADO DE MADEIRA R9,est_ESTRADO DE MADEIRA RD,est_ESTRADO DE MADEIRA X1,est_ESTRADO DE MADEIRA Z4
0,12,51-01145,"BD-CY 99X143,5 1KG CHOURIÇO SICASAL",2,10.0,51-43693,"F1 950x888,8x0,22 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,...,0,0,0,0,0,0,0,0,0,0
1,37,51-01172,BD-CY 99x118 ST EC CL,1,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,...,0,0,0,0,0,0,0,0,0,0
2,57,51-01215,BD-CY 99x118 1T ST ESMALTE INDUSTRIAL,2,10.0,51-74554,"F1 866x941,8x0,18 E2,0 TH550",LT,BAAAAABAD,866.0,...,0,0,0,0,0,0,0,0,0,0
3,100,51-01615,BD-CY 150x188 25P SALS.SICASAL,2,10.0,51-43971,"F1 950x775x0,26 D2,8/2,0 TH415",LT,BAAAAABAD,950.0,...,0,0,0,0,0,0,1,0,0,0
4,114,51-01799,BD-TC 180x235 P IC GD EC WC 3KG AZEITONA,2,10.0,51-63743,"F1 761x1075x0,25 D2,8/2,0 TS275",LT,BAAAAABAD,761.0,...,0,0,0,0,0,0,0,0,0,0

Shape df4 5: (1840, 67)

In [97]:
# Without Estrato Madeira

df4_5 = df4_4

#### Texto Breve Material

In [98]:
# data processing for Texto breve material

df4_6 = df4_5.copy()

for idx, component in enumerate(df4_6["Texto breve de material"]):
#     print(component)
    flag = 0;
    c = component.split(" ")
    c = list(filter(None, c))
    if len(c) <= 2:
        continue
    else:
        if 'F.PREP' in c[0]:
            f_prep = 1
            car1_1 = c[1]
            if "LI" in car1_1:
                li0_bd1 = 0
            elif "BD" in car1_1:
                li0_bd1 = 1
            try:
                if 'x' in c[2]:
                    c1 = c[2].split("x")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                elif 'X' in c[2]:
                    c1 = c[2].split("X")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                else:
                    try:
                        dim1_1 = float(c[2].replace(',','.')) ; dim1_2 = np.nan
                    except:
                        print("Error with: ", component) ; flag = 1
            except:
                print("Error with: ", component) ; flag = 1
        else:
            f_prep = 0
            car1_1 = c[0]
            if "LI" in car1_1:
                li0_bd1 = 0
            elif "BD" in car1_1:
                li0_bd1 = 1
            try:
                if 'x' in c[1]:
                    c1 = c[1].split("x")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                elif 'X' in c[1]:
                    c1 = c[1].split("X")
                    dim1_1 = float(c1[0].replace(',','.')) ; dim1_2 = float(c1[1].replace(',','.'))
                else:
                    try:
                        dim1_1 = float(c[1].replace(',','.')) ; dim1_2 = np.nan
                    except: 
                        print("Error with: ", component) ; flag = 1
            except: 
                print("Error with: ", component) ; flag = 1
        
        if flag == 0:
            column_indexer = {'dim1_1':dim1_1, 'dim1_2':dim1_2, 'car1_1':car1_1, 'f_prep':f_prep, 'li_bd':li0_bd1}
            for x in column_indexer:
                df4_6.loc[idx,x]=column_indexer[x]
    
df4_6.dropna(subset = ["dim1_1"], inplace=True)

display(df4_6.tail())
print("Shape df3 6:", df4_6.shape)

Error with:  LI-LD 286-292 P EC WC
Error with:  AMOSTRAS CORPOS LITOGRAFADOS
Error with:  LI-RG 188/LI-BT 170 EC CL (NEW SPEC)
Error with:  LI-RG 188/LI-BT 170 EC GD (NEW SPEC)
Error with:  F.PREP BD-TL 188/CY 170/TC 180 EC WC0,25
Error with:  BD-CY 284/273x240 FT EC WC
Error with:  LI-LD 286/292 P IC PGB EC WC SCR
Error with:  LI-LD 286/292 P IC PGB EC WC SCR P/ FURA
Error with:  F.PREP BD-TL 188/TC 180 IC PGB EC WC0,23
Error with:  LI-RG 188/LI-BT 170 IC PGB EC GD NS(803)
Error with:  LI-RG 188/LI-BT 170 IC PGB EC CL(NEW SP)
Error with:  F.PREP BD-CY 99x...IC PGC EC WC(NSTH550)
Error with:  F.PREP BD-TL 188/TC180 IC PGB EC WC 0,23
Error with:  F.PREP BD-TL 188/TC180 EC WC 0,23 NEW
Error with:  LI-LD 62/80 IC PGB EC WC (CANUDAS)
Error with:  F.PREP BD-CY 99x... EC CL (NS TH550)
Error with:  F.PREP BD-CY 99x... EC WC (NS TH550)
Error with:  LI-LD 62/80 IC PGB EC CL (CANUDAS)
Error with:  F.PREP BD-TL 188/CY 170 IC PGB ECWC0,25.
Error with:  F.PREP BD-CY 99x... EC WC (TITAN)
Error with:  F.PREP BD-TL 188/CY170/TC 180 EC WC0,25.
Error with:  F.PREP BD-TL188/TC180 IC PGB EC WC 0,25.
Error with:  F.PREP BD-CY 170/TC 180 EC CL
Error with:  F.PREP BD-CY 170/TC 180 EC WC
Error with:  F.PREP BD-CY 170x... EC WC
Error with:  F.PREP BD-CY 170/TC 180 IC PGC EC WC
Error with:  F.PREP BD-TL 188/TC 180 IC PGB EC CL0,25
Error with:  F.PREP BD-CY 273/284x235 EC CL
Error with:  F.PREP BD-CY 273/284x240 EC WC
Error with:  F.PREP BD-CY 273/284x372 EC WC
Error with:  F.PREP BD-CY 273/284x472 EC WC 0,43
Error with:  F.PREP BD-CY 273/284x472 IC GD EC WC0,43
Error with:  F.PREP BD-CY 273/284x463 EC WC
Error with:  F.PREP BD-CY 273/284x240 EC CL
Error with:  F.PREP BD-CY 273/284x372 EC CL
Error with:  F.PREP BD-CY 273/284x445 EC CL
Error with:  F.PREP BD-CY 273/284x463 EC CL
Error with:  F.PREP BD-CY BD-CY 65x75 EC CL
Error with:  F.PREP BD-TL188x197 1T IC PGB EC WC(TIT.
Error with:  F.PREP BD-AE 65x* EC WC 1D (COIL 931)
Error with:  F.PREP BD-AE 65x* EC WC (COIL 931)
Error with:  F.PREP BD-AE 65x* IC GD EC WC (COIL 931)
Error with:  BD-TC292x366 N P UN CR2ICGD J CMP B HEST
Error with:  F.PREP BD-AE 65x* IC GD EC WC(COIL 931).
Error with:  F.PREP BD-AE 65x* EC WC (COIL 931).

,index,Material,Texto breve de material,Nível,Nº item,Componente,Texto breve objeto,Setor de atividade,Grupo de mercadorias,dim1,dim2,dim3,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd
1834,50447,51-71700,"F.PREP BD-AE 49x119 2ICGD ECWC 1D(0,17).",1,10.0,51-71694,"F1 931x740x0,17 E2,8 TS290.",LT,BAAAAABAD,931.0,740.0,0.17,"E2,8",TS290.,ESM BRANCO HB-367 A,49.0,119.0,BD-AE,1.0,1.0
1835,50456,51-71701,"F.PREP BD-AE 49x119 EC CL 2XIC GD(0,17).",1,10.0,51-71694,"F1 931x740x0,17 E2,8 TS290.",LT,BAAAAABAD,931.0,740.0,0.17,"E2,8",TS290.,NaN,49.0,119.0,BD-AE,1.0,1.0
1836,50465,51-71813,F.PREP BD-TC 286x370 PL IC PGB HESTEEL,1,10.0,51-70560,"F1 837x813x0,28 E2,0 TS275 HESTEEL.",LT,BAAAAABAD,931.0,740.0,0.17,"E2,8",TS290.,NaN,286.0,370.0,BD-TC,1.0,1.0
1837,50473,51-71896,"F.PREP BD-AE 49x185 IC GD EC WC 0,17",1,10.0,51-70511,"F1 931X759X0,17 2,0/2,8D TS340",LT,BAAAAABAD,931.0,759.0,0.17,"2,0/2,8D",TS340,ESM BRANCO HB-367 A,49.0,185.0,BD-AE,1.0,1.0
1839,50491,SLILD 286 PP,SLI_LD 286 PP,1,10.0,51-63064,"F1 750x705x0,23 E2,8 TS275",LT,BAAAAABAD,750.0,705.0,0.23,"E2,8",TS275,ESMALTE 135.262,286.0,NaN,SLI_LD,0.0,0.0

Shape df3 6: (1793, 20)

In [99]:
print(df4_6.isna().sum())

index                        0
Material                     0
Texto breve de material      0
Nível                        0
Nº item                      0
Componente                   0
Texto breve objeto           0
Setor de atividade           0
Grupo de mercadorias         0
dim1                         0
dim2                         0
dim3                         0
car1                         0
car2                         0
esm                        635
dim1_1                       0
dim1_2                     281
car1_1                       0
f_prep                       0
li_bd                        0
dtype: int64

In [100]:
drop_columns = ['index', 'Texto breve de material', 'Nível', 'Nº item', 'Componente', 'Texto breve objeto', 'Setor de atividade', 'Grupo de mercadorias']
df4_6.drop(drop_columns, axis=1, inplace=True, errors='ignore')

# print(df4_6.nunique())
print(df4_6.keys())

Index(['Material', 'dim1', 'dim2', 'dim3', 'car1', 'car2', 'esm', 'dim1_1',
       'dim1_2', 'car1_1', 'f_prep', 'li_bd'],
      dtype='object')

### Join dataframes from "Material"

In [101]:
df_columns = []

# Concatenate material's df
frames = [df3_6, df4_6]
materials = pd.concat(frames)
materials.drop_duplicates(inplace=True)

# Merge df with order with material description
df6 = pd.merge(df_teste, materials, how='left', on='Material')

display(materials.head())
print("Shape (Materials):", materials.shape)
display(df6.head())
print("Shape df6:", df6.shape)
print("Shape df5:", df_teste.shape)

,Material,dim1,dim2,dim3,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd
0,51-00855,761.0,1075.0,0.25,"D2,8/2,0",TS275,ESM BRANCO HB-367 A,188.0,NaN,BD-TL,1.0,1.0
1,51-00882,835.0,1106.0,0.23,"E2,8",TS275,ESM BRANCO HB-367 A,180.0,120.0,BD-RC,1.0,1.0
2,51-01163,866.0,941.8,0.18,"E2,0",TH550,ESM BRANCO HB-367 A,99.0,118.0,BD-CY,0.0,1.0
3,51-02791,850.0,1006.0,0.23,"D2,8/2,0",TS275,ESM BRANCO HB-367 A,106.0,76.0,BD-RC,0.0,1.0
4,51-03931,833.0,806.5,0.20,"D2,8/2,0",TS275,ESM BRANCO HB-367 A,65.0,157.0,BD-AE,0.0,1.0

Shape (Materials): (3820, 12)

,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,ab,...,dim2,dim3,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd
0,1000231619,1,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ PIGMENTADO,722,722,6,6,LE04,C06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1000231619,2,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,716,716,67,67,LE02,C06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1000231619,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,649,649,7,7,LE02,C06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1000231619,4,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,642,642,47,47,LI17,C06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1000231619,5,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,595,595,16,16,LI05,C06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Shape df6: (39028, 40)
Shape df5: (39028, 29)

In [102]:
# df6[df6["Material"] == '51-00882']
df7 = df6[~df6["dim2"].isnull()]
df7.reset_index(inplace=True)

display(df7.head())
print("Shape:", df7.shape)

,index,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,...,dim2,dim3,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd
0,6,1000234824,1,APLICAÇÃO DE VERNIZ,1ª APLICAÇÃO DE VERNIZ OURO INTERIOR,5305,5305,63,63,LE04,...,813.0,0.38,"E2,0",TS275,ESMALTE 135.262,286.0,NaN,LI-LD,0.0,0.0
1,7,1000234824,2,APLICAÇÃO DE VERNIZ,2ª APLICAÇÃO DE VERNIZ OURO INTERIOR,5242,5242,11,11,LE04,...,813.0,0.38,"E2,0",TS275,ESMALTE 135.262,286.0,NaN,LI-LD,0.0,0.0
2,8,1000234824,3,APLICAÇÃO DE ESMALTE BRANCO,APLICAÇÃO DE ESMALTE BRANCO,5231,5231,71,71,LE06,...,813.0,0.38,"E2,0",TS275,ESMALTE 135.262,286.0,NaN,LI-LD,0.0,0.0
3,9,1000234824,4,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,5160,5160,181,181,LI05,...,813.0,0.38,"E2,0",TS275,ESMALTE 135.262,286.0,NaN,LI-LD,0.0,0.0
4,10,1000234824,5,CORTE DE FOLHA,CORTE DE FOLHA,4979,4979,22,22,CS11,...,813.0,0.38,"E2,0",TS275,ESMALTE 135.262,286.0,NaN,LI-LD,0.0,0.0

Shape: (33460, 41)

In [103]:
for i in df7.keys():
    print("%s --> %d"%(i , df7[i].isna().sum()))

index --> 0
Ordem --> 0
n_operations --> 0
Tipo de operação --> 0
Tipo de operação n2 --> 0
Qtd.ordem --> 0
out_Qtd.ordem --> 0
dif --> 0
out_defects --> 0
CT --> 0
ab --> 0
ac --> 0
Grupo Mercadorias --> 0
ad --> 0
ae --> 0
af --> 0
Hierarquia prod --> 0
Material --> 0
Qtd.ordem_old --> 0
Qtd.confirmada --> 0
Iníc.real --> 0
DtaRealFim --> 0
Mês --> 0
DD --> 0
controlo --> 0
data_teste --> 0
start_date --> 931
end_date --> 931
Difference --> 931
week_day --> 931
dim1 --> 0
dim2 --> 0
dim3 --> 0
car1 --> 0
car2 --> 0
esm --> 12065
dim1_1 --> 0
dim1_2 --> 6913
car1_1 --> 0
f_prep --> 0
li_bd --> 0

### Remove large variations in the number of defects

In [104]:
df7["var"] = abs(df7["out_defects"])*100/df7["Qtd.ordem"]

df7.loc[df7["var"] > 70, "outliers"] = True
df7.loc[df7["var"] <= 70, "outliers"] = False 

df7.drop(df7[df7["outliers"] == True].index, inplace=True)

### Remove negative number of defects

In [105]:
df8 = df7[df7['out_defects'] >= 0]
print("Minimum number:", df7['out_defects'].min())

ranges = [-2000, -1000, -100, -30, -10, -1, 0, 3, 5,10,20,30,50,100,1000,10000]
display(df7['out_defects'].groupby(pd.cut(df7['out_defects'], ranges)).count())

df7[df7['out_defects'] <= -1000].head()

Minimum number: -1352

out_defects
(-2000, -1000]        4
(-1000, -100]       453
(-100, -30]        1706
(-30, -10]         2467
(-10, -1]          2912
(-1, 0]           10205
(0, 3]             2233
(3, 5]             1163
(5, 10]            1958
(10, 20]           2378
(20, 30]           1598
(30, 50]           1965
(50, 100]          2260
(100, 1000]        1960
(1000, 10000]        99
Name: out_defects, dtype: int64

,index,Ordem,n_operations,Tipo de operação,Tipo de operação n2,Qtd.ordem,out_Qtd.ordem,dif,out_defects,CT,...,car1,car2,esm,dim1_1,dim1_2,car1_1,f_prep,li_bd,var,outliers
6714,8174,1000247968,3,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,4992,4992,-1138,-1138,LE02,...,"2,0/2,8D",TS275,ESM BRANCO 819.904,52.0,161.0,BD-AE,0.0,1.0,22.796474,False
6715,8175,1000247968,3,APLICAÇÃO DE VERNIZ,APLICAÇÃO DE VERNIZ DE ACABAMENTO,4992,4992,-1138,-1138,LE02,...,"2,0/2,8D",TS275,ESM BRANCO 819.904,52.0,161.0,BD-AE,0.0,1.0,22.796474,False
7425,9003,1000248302,1,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,2530,2530,-1352,-1352,LI15,...,"D2,8/2,0",TS275,ESM BRANCO HB-367 A,65.0,157.0,BD-AE,0.0,1.0,53.438735,False
31119,36520,1000259781,1,APLICAÇÃO DE TINTA DE IMPRESSÃO,APLICAÇÃO DE TINTA DE IMPRESSÃO,30750,30750,-1128,-1128,LI17,...,"2,0/2,8D",TS275,ESM BRANCO HB-367 A,57.0,207.0,BD-AE,0.0,1.0,3.668293,False

#### Other ajustments

In [106]:
df7.drop(df7[df7["Tipo de operação"] == "APLICAÇÃO DE TINTA DE IMPRESSÃO, APLICAÇÃO DE VERNIZ"].index, inplace=True)

df7["Tipo de operação"].unique()

array(['APLICAÇÃO DE VERNIZ', 'APLICAÇÃO DE ESMALTE BRANCO',
       'CORTE DE FOLHA', 'APLICAÇÃO DE TINTA DE IMPRESSÃO', 'EMBALAMENTO'],
      dtype=object)

#### Add some negative number of defects

In [107]:
df8_1 = df7[df7['out_defects'] >= -3]
df8_2 = df8_1.copy()
mask_1 = df8_1.out_defects <= 5
mask_2 = df8_2.out_defects <= 7

column_name = 'out_defects'
df8_1.loc[mask_1, column_name] = 0
df8_2.loc[mask_2, column_name] = 0

print('df8_1')
display(df8_1['out_defects'].groupby(pd.cut(df8_1['out_defects'], ranges)).count())
print('df8_2')
display(df8_2['out_defects'].groupby(pd.cut(df8_2['out_defects'], ranges)).count())

df8_1

out_defects
(-2000, -1000]        0
(-1000, -100]         0
(-100, -30]           0
(-30, -10]            0
(-10, -1]             0
(-1, 0]           14814
(0, 3]                0
(3, 5]                0
(5, 10]            1958
(10, 20]           2378
(20, 30]           1598
(30, 50]           1965
(50, 100]          2260
(100, 1000]        1960
(1000, 10000]        99
Name: out_defects, dtype: int64

df8_2

out_defects
(-2000, -1000]        0
(-1000, -100]         0
(-100, -30]           0
(-30, -10]            0
(-10, -1]             0
(-1, 0]           15582
(0, 3]                0
(3, 5]                0
(5, 10]            1190
(10, 20]           2378
(20, 30]           1598
(30, 50]           1965
(50, 100]          2260
(100, 1000]        1960
(1000, 10000]        99
Name: out_defects, dtype: int64

### Export to CSV

In [108]:
# df1.to_csv(name + r' - processed.csv', index = False)


# # For every column, use df6 instead of df7
# df6.to_csv(r'teste df6 - processed.csv', index = False)

# # Export data with materials description
# df7.to_csv(r'data with n_defects and materials - processed.csv', index = False)

# Export data with materials description (only without defects)
df8_1.to_csv(r'test - processed 1.csv', index = False)

# Export data with materials description (only without defects)
df8_2.to_csv(r'test - processed 2.csv', index = False)

---
### Backup

---
### Hide code

In [ ]:
# from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
The raw code for this IPython notebook is by default hidden for easier reading.
To toggle on/off the raw code, click <a href="javascript:code_toggle()">here</a>.''')